services:
  api:
    container_name: loggernaut-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      #- "80:443"
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - loggernaut-api
    volumes:
      - loggernaut-inbox:/data/inbox
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  mongodb:
    container_name: loggernaut-db
    restart: unless-stopped
    image: mongodb/mongodb-community-server
    networks:
      - loggernaut-api
    volumes:
      - loggernaut-db:/data/db

volumes:
  loggernaut-inbox:
  loggernaut-db:

networks:
  loggernaut-api:
    driver: bridge